language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: ui.e@klarna.com
  api_key:
    secure: NxBeqPeKk87y7CN6aJ3DMaGeHD+6MV+dz015O9OFUDOyYUnl0Rr3+1O7Br/288WiIiuOKPQgGjHzUL1kbdo8d+1VkvRm/X7TWUCkPUrMF4R5mIOcwiupfL8wP+4ynHEN+JVFuAV2uKy5we7xB22/mRhm9Ow2+TQErE2INtUdd22m6KLKThhAIqMIZd3JEmjYAwcFs/Z98KcgurKkaPcJlovXsBYFvzcKUpPV5L/6RthFtLG0dzkwUC4agle1pXqRI2PDP1MMifhSTuzt6OUIxWsEogp/9kFw3juiM5vlJUhUvpJd7p38YkTAmZnlzKClC8OZ009b7NsFGo+90NZForJ0iH7A2AFhizFeHhd95RFmbb8wVbLF0fyjcpvgusdyh8+9wlj9OshrOZbjp75WFG0npR00m6qHP+lnfSLnuk9C/WQLkvO3V2cpMkbkcopcXwucRXma2Fqs//MtJfUdm3l1xWTVkPr2m2xHqtGmPLjdWDs9WQcAANDJ7f3myaCucvDk1fLcmRMDbAt9hqSLZZLj0aBhN9A9de8Z5MKW6sbT0BzyNRVYHkB/cJBYU5p7fd/gHFUYtvwJt+24whK2CQYMUDdM50nqaEp11a8AIIv8/7dvfkH6u6a0M3nVuAZbBpwVYOEIYMXy4w4Nm1i+va/uDN1JRXPK8BExvLYS8/A=
  on:
    tags: true
    repo: klarna/remote-frames
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+/
